apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-payment
  template:
    metadata:
      labels:
        app: ms-payment
    spec:
      containers:
        - name: ms-payment
          image: 640168416591.dkr.ecr.us-east-1.amazonaws.com/fastfood/ms-payment:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ms-payment-secret
                  key: postgres_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ms-payment-secret
                  key: postgres_port
                  optional: true
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ms-payment-secret
                  key: postgres_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-payment-secret
                  key: postgres_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ms-payment-secret
                  key: postgres_database
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3001
            initialDelaySeconds: 10 # Aguarde 10s antes da primeira verificação
            periodSeconds: 5 # Verifica a cada 5s
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ms-payment
spec:
  type: LoadBalancer
  selector:
    app: ms-payment
  ports:
    - port: 80
      targetPort: 3001
